name: intercom
description: Flutter Intercom integration
version: 0.0.1
author: Maido Käära <maido@getchange.com>
homepage: https://github.com/ChangeFinance/intercom_flutter

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.getchange.intercom
    pluginClass: IntercomPlugin
